project_name: nvr-go

builds:
  - id: nvr
    dir: ./nvr-go
    main: ./
    binary: nvr
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    ignore:
      - goos: darwin
        goarch: arm

archives:
  - id: tar
    builds:
      - nvr
    format: tar.gz
    wrap_in_directory: false
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{- tolower .Os -}}_{{- if eq .Arch "arm" -}}armv{{ .Arm }}{{- else -}}{{ .Arch }}{{- end -}}

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

release:
  github:
    owner: neomux
    name: neomux

changelog:
  sort: asc
